services:
  ngrok:
    image: ngrok/ngrok:latest
    command:
      - http
      - n8n:5678
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040" # ngrok web UI/API
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    depends_on:
      - ngrok
    ports:
      - "5678:5678"
    volumes:
      - ./:/home/node/.n8n
      - ./scripts:/home/node/scripts
    environment:
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - DB_TYPE=${DB_TYPE}
      - DB_SQLITE_DATABASE=${DB_SQLITE_DATABASE}
    command: ["sh", "-c", "/home/node/scripts/entrypoint.sh"]
    restart: unless-stopped
